# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788a9a64882076b11db3c59188b014dd105c0599dcdce65e771bd551ff7c25550261e2fc74af962f935e442a547c9edae2d5cfa5a3f90bbab5bcdec8e3ff3e7c

test:
  secret_key_base: 87a0d5e1c29da81d3191db7069d94b084ee1128d5f471aefdf15751e34f4e654a3c27c4b146f6bd5ff16c932abdb11c9f68be10dfc7da4f64f807c9bd630c41d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
